services:
  - type: web
    name: urbaneye-backend
    env: docker
    rootDir: backend
    plan: free

  - type: web
    name: urbaneye-frontend
    env: static
    rootDir: website
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://urbaneye-backend.onrender.com
