name: urbaneye_mobile

version: 0.1.0+1

publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.12.0+2
  camera_android: ^0.10.10
  tflite_flutter: ^0.12.1
  path_provider: ^2.1.5
  geolocator: ^14.0.3
  http: ^1.6.0
  image_picker: ^1.2.3
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/models/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
